accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUp.as_view(), name='signup'),
]

reddit_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomepageView.as_view(), name="homepage"),
    path('accounts', include('accounts.urls', namespace='accounts')),
    path('accounts', include('django.contrib.auth.urls')),
    path('test', views.TestPageView.as_view(), name="test"),
    path('thanks', views.ThanksPageView.as_view(), name="thanks")
]

accounts/models.py
from django.db import models
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return f"@{self.username}"

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'password1', 'password2')
        model = get_user_model()

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms


class SignUp(CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

reddit_clone/views.py
from django.views.generic import TemplateView


class HomepageView(TemplateView):
    template_name = "index.html"


class TestPageView(TemplateView):
    template_name = "test.html"


class ThanksPageView(TemplateView):
    template_name = "thanks.html"

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>Log In</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-info">
    </form>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-info">
    </form>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>SpacedIt</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <a class="navbar-brand" href="{% url 'homepage' %}">SpacedIt</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="" class="nav-link">Post</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a href="" class="nav-link">Create Group</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="" class="nav-link">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:login' %}" class="nav-link">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'accounts:signup'%}" class="nav-link">Sign Up</a>
                    </li>
            {% endif %}
    </ul>
  </div>
</nav>

    <div class="container my-4">
    {% block content %}

    {% endblock %}
    </div>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content%}
<h1>Welcome to SpacedIt!</h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}

{% block content %}

<h1>You are now logged In</h1>

{% endblock content %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h1>You are now logged out</h1>
{% endblock content %}